package com.moronigranja.localttsreader.spiketts

import ai.onnxruntime.OrtEnvironment
import ai.onnxruntime.OrtSession
import android.content.Context
import android.os.Build
import android.os.Debug
import com.moronigranja.localttsreader.tts.DefaultEngines
import com.moronigranja.localttsreader.tts.SynthesisOutcome
import com.moronigranja.localttsreader.tts.SynthesisRequest
import com.moronigranja.localttsreader.tts.kokoro.KokoroEngine
import com.moronigranja.localttsreader.tts.kokoro.KokoroPacks
import com.moronigranja.localttsreader.tts.kokoro.PhonemizeException
import com.moronigranja.localttsreader.tts.kokoro.Phonemizer
import kotlinx.coroutines.runBlocking
import org.json.JSONArray
import org.json.JSONObject
import java.io.File
import kotlin.math.abs
import kotlin.system.measureTimeMillis

/**
 * The Kokoro on-device benchmark (decisions #30 device half), shared by the
 * interactive [KokoroActivity] and the instrumented
 * `KokoroDeviceBenchmarkTest` (which runs on a locked/off screen — the
 * realistic player condition).
 *
 * Phonemization is the only excluded stage: the corpus ships pre-phonemized
 * raw espeak-ng output (host-generated by `:core-tts:kokoroGrainSpike`), and
 * a passthrough [Phonemizer] answers for the corpus texts. Everything
 * downstream — vocab filter, chunker, windows, ORT inference, trim, pause
 * insertion — runs verbatim in the engine.
 *
 * D2 — execution-provider comparison (measurement only; no production change):
 * each provider (CPU / XNNPACK / NNAPI / qnn-htp) runs its own pass and writes
 * `kokoro_results_<label>.json`. Every non-CPU candidate is ORACLE-gated: the
 * same corpus is synthesized with a CPU oracle and peak/mean absolute PCM
 * amplitude deltas across the corpus are reported; a candidate whose max
 * abs diff exceeds [ORACLE_REJECT_THRESHOLD] or any passage errors is recorded
 * as rejected. Cold engine-open ms (the D1 metric) is captured per provider.
 * A candidate that cannot initialize logs `candidate <label> unavailable` and
 * is skipped while CPU still completes. Default deployment stays CPU.
 *
 * D3 — model-precision spike (measurement only): fp16 / int8 / q8 models run on
 * CPU EP, each oracle-gated against the pinned fp32, writing
 * `kokoro_precision_<label>.json`.
 */
class KokoroBenchmarkRunner(
    private val context: Context,
) {
    init {
        QnnEp.libDir = context.applicationInfo.nativeLibraryDir
    }

    /** Execution providers compared on-device (D2). */
    enum class OrtProvider(
        val label: String,
        val options: (OrtSession.SessionOptions) -> Unit,
    ) {
        CPU("cpu", {}),
        XNNPACK("xnnpack", { it.addXnnpack(mapOf("intra_op_num_threads" to "6")) }),
        NNAPI("nnapi", { it.addNnapi() }),
        QNN_HTP("qnn-htp", { so -> QnnEp.install(so) }),
    }

    /** Model precisions for the D3 spike (all run on CPU EP). */
    enum class ModelPrecision(
        val label: String,
        val fileName: String,
    ) {
        FP16("fp16", "kokoro-model-fp16"),
        INT8("int8", "kokoro-model-int8"),
        Q8("q8", "kokoro-model-q8"),
    }

    companion object {
        const val RUNS = 3
        const val ORACLE_REJECT_THRESHOLD = 0.001f // max abs diff gate for adoption (decision #67 rule b)
        private val VOICES = mapOf("en-us" to "af_heart", "pt-br" to "pf_dora")
    }

    /**
     * Registers the QNN plugin EP once (stock ORT needs no custom build) and
     * enables the HTP (NPU) backend. Unsupported ops fall back to CPU per
     * subgraph; a failed graph build surfaces as candidate-unavailable.
     */
    private object QnnEp {
        private var registered = false

        /** App native lib dir; parent of libQnnHtp.so → drives ADSP_LIBRARY_PATH. */
        var libDir: String? = null

        fun install(options: OrtSession.SessionOptions) {
            val env = OrtEnvironment.getEnvironment()
            if (!registered) {
                // Trivial constants from the plugin AAR (ai.onnxruntime.qnnpluginep).
                env.registerExecutionProviderLibrary("QNNExecutionProvider", "libonnxruntime_providers_qnn.so")
                registered = true
            }
            val devices = env.epDevices.filter { it.epName == "QNNExecutionProvider" }
            // Absolute backend_path so the EP sets ADSP_LIBRARY_PATH to the lib
            // dir (empty otherwise → HTP device create fails). EP 2.5.0 rejects
            // v79 arch values, so pin the SoC numerically instead: SM8850 = 87
            // (QAIRT Qnn_SocModel_t, per soc_utils.cc in onnxruntime-qnn main).
            val nativeLibDir = checkNotNull(libDir) { "native lib dir not initialized" }
            options.addExecutionProvider(
                devices,
                mapOf(
                    "backend_path" to "$nativeLibDir/libQnnHtp.so",
                    "soc_model" to "87",
                ),
            )
        }
    }

    private val models = File(context.filesDir, "models")
    private val corpusFile = File(context.filesDir, "corpus.tsv")

    /** Runs every provider; returns true if CPU completed (candidates may be unavailable). */
    fun run(log: (String) -> Unit): Boolean {
        var cpuOk = false
        for (provider in OrtProvider.entries) {
            val ok = run(provider, log)
            if (provider == OrtProvider.CPU && ok) cpuOk = true
        }
        for (precision in ModelPrecision.entries) {
            runPrecision(precision, log)
            runQnnPrecision(precision, log)
        }
        return cpuOk
    }

    /**
     * Runs a single candidate pass (provider or precision); returns true when
     * its own runs completed. A candidate that fails to initialize logs
     * unavailable and returns false without aborting the batch.
     */
    private fun measure(
        label: String,
        modelFileName: String,
        options: (OrtSession.SessionOptions) -> Unit,
        oracleModelFileName: String?, // null → no oracle (CPU EP baseline pass)
        runs: Int, // CPU EP baseline → RUNS, else 1
        capstone: Boolean, // true only for CPU EP baseline (espeak full-pipeline block)
        resultFileName: String,
        log: (String) -> Unit,
    ): Boolean {
        val outDir = context.getExternalFilesDir(null) ?: context.filesDir
        return try {
            check(File(models, modelFileName).isFile && File(models, "kokoro-voices").isFile) {
                "models not found under ${models.absolutePath} — stage them first (see build.md)"
            }
            if (oracleModelFileName != null && oracleModelFileName != modelFileName) {
                check(File(models, oracleModelFileName).isFile) { "oracle model not staged: $oracleModelFileName" }
            }
            check(corpusFile.isFile) { "corpus not found at ${corpusFile.absolutePath}" }

            val entries =
                corpusFile.readLines().mapNotNull { line ->
                    val parts = line.split('\t')
                    if (parts.size != 3) null else Triple(parts[0], parts[1], parts[2])
                }
            check(entries.isNotEmpty()) { "corpus.tsv is empty or malformed" }
            val lookup = entries.associate { it.first to it.third }
            val languages = entries.map { it.second }.toSet()
            log("candidate=$label device: ${Build.MANUFACTURER} ${Build.MODEL}, sdk ${Build.VERSION.SDK_INT}")
            log("corpus: ${entries.size} passages (${languages.sorted()}); phonemization = host-precomputed")

            // Cold engine-open (D1 metric) on this provider's factory.
            val tOpen = System.currentTimeMillis()
            val engine =
                KokoroEngine.open(
                    spec = DefaultEngines.kokoro,
                    packs = KokoroPacks.all,
                    modelFile = File(models, modelFileName),
                    voicesFile = File(models, "kokoro-voices"),
                    phonemizer = CorpusPhonemizer(lookup, languages),
                    progress = { log("open stage: $it (${System.currentTimeMillis() - tOpen} ms)") },
                    sessionFactory = options,
                )
            val engineOpenMs = System.currentTimeMillis() - tOpen
            log("engine open: $engineOpenMs ms (candidate=$label)")

            // Oracle engine: opened only for oracle-gated candidates.
            var oracle: KokoroEngine? = null
            if (oracleModelFileName != null) {
                val tO = System.currentTimeMillis()
                oracle =
                    KokoroEngine.open(
                        spec = DefaultEngines.kokoro,
                        packs = KokoroPacks.all,
                        modelFile = File(models, oracleModelFileName),
                        voicesFile = File(models, "kokoro-voices"),
                        phonemizer = CorpusPhonemizer(lookup, languages),
                        progress = {},
                        sessionFactory = OrtProvider.CPU.options,
                    )
                log("oracle engine open: ${System.currentTimeMillis() - tO} ms (provider=cpu)")
            }

            val thermal = ThermalProbe(context)
            thermal.start()
            val results = JSONObject()
            val runsJson = JSONArray()
            val passes = runs
            var maxAbsDiff = 0f
            var meanAbsDiffSum = 0.0
            var diffCount = 0
            var oracleMillisTotal = 0L
            var oracleErrors = 0
            for (run in 1..passes) {
                val runJson = JSONObject().put("run", run)
                val passagesJson = JSONArray()
                for ((text, language, _) in entries) {
                    val voice = VOICES[language] ?: error("no voice mapped for corpus language '$language'")
                    var outcome: SynthesisOutcome? = null
                    val millis =
                        measureTimeMillis {
                            outcome = runBlocking { engine.synthesize(SynthesisRequest(text, voice)) }
                        }
                    when (val result = outcome) {
                        null -> error("synthesis returned null outcome")
                        is SynthesisOutcome.Audio -> {
                            val seconds = result.pcm.size / 2.0 / KokoroEngine.SAMPLE_RATE
                            val rtf = millis / 1000.0 / seconds
                            passagesJson.put(
                                JSONObject()
                                    .put("language", language)
                                    .put("voice", voice)
                                    .put("synth_ms", millis)
                                    .put("audio_seconds", seconds)
                                    .put("rtf", rtf)
                                    .put("samples", result.pcm.size / 2),
                            )
                            log(
                                "run $run [$language/$voice]: ${"%.2f".format(seconds)}s audio in " +
                                    "$millis ms, RTF=${"%.3f".format(rtf)} (candidate=$label)",
                            )
                            Wav.write(
                                File(outDir, "kokoro_${label}_run${run}_$language.wav"),
                                pcmToFloats(result.pcm),
                                KokoroEngine.SAMPLE_RATE,
                            )
                            // Oracle gate (D2): candidate vs CPU on the same corpus.
                            if (oracle != null) {
                                var oracleOutcome: SynthesisOutcome? = null
                                val oMillis =
                                    measureTimeMillis {
                                        oracleOutcome =
                                            runBlocking {
                                                oracle.synthesize(SynthesisRequest(text, voice))
                                            }
                                    }
                                val oRes = oracleOutcome as? SynthesisOutcome.Audio
                                if (oRes == null) {
                                    oracleErrors++
                                    log("  oracle [$language]: FAILED ($oracleOutcome)")
                                } else {
                                    Wav.write(
                                        File(outDir, "kokoro_${label}_oracle_$language.wav"),
                                        pcmToFloats(oRes.pcm),
                                        KokoroEngine.SAMPLE_RATE,
                                    )
                                    val (peak, mean) =
                                        pcmDiff(pcmToFloats(result.pcm), pcmToFloats(oRes.pcm))
                                    maxAbsDiff = maxOf(maxAbsDiff, peak)
                                    meanAbsDiffSum += mean
                                    diffCount++
                                    oracleMillisTotal += oMillis
                                    log(
                                        "  oracle [$language]: peak=${"%.6f".format(peak)} " +
                                            "mean=${"%.6f".format(mean)} (${oMillis}ms)",
                                    )
                                }
                            }
                        }
                        is SynthesisOutcome.Failed -> throw IllegalArgumentException("synthesis failed [$language]: ${result.reason}")
                        SynthesisOutcome.Unavailable -> error("packs not ready on device")
                    }
                }
                runJson.put("passages", passagesJson)
                runsJson.put(runJson)
            }
            thermal.stop()
            val mem = Debug.MemoryInfo()
            Debug.getMemoryInfo(mem)
            val meanAbsDiff = if (diffCount > 0) (meanAbsDiffSum / diffCount).toFloat() else 0f
            results.put("provider", label)
            results.put("runs", runsJson)
            results.put("vm_hwm_kb", readVmHwm())
            results.put("total_pss_kb", mem.totalPss)
            results.put("thermal_status_max", thermal.maxStatus)
            results.put("thermal_headroom_max", thermal.maxHeadroom)
            results.put("screen", "off/locked (instrumented)")
            results.put("threads", 6)
            results.put("device", "${Build.MANUFACTURER} ${Build.MODEL}")
            results.put("engine_open_ms", engineOpenMs)
            results.put("phonemization", "excluded (host-precomputed corpus; espeak-ng cost is ~ms/sentence)")
            if (oracle != null) {
                val rejected = oracleErrors > 0 || maxAbsDiff > ORACLE_REJECT_THRESHOLD
                results.put("oracle_compared_against", "cpu")
                results.put("oracle_synth_ms_total", oracleMillisTotal)
                results.put("max_abs_diff", maxAbsDiff)
                results.put("mean_abs_diff", meanAbsDiff)
                results.put("oracle_errors", oracleErrors)
                results.put("oracle_rejected", rejected)
                log(
                    "oracle gate: max_abs_diff=${"%.6f".format(maxAbsDiff)} " +
                        "mean_abs_diff=${"%.6f".format(meanAbsDiff)} errors=$oracleErrors rejected=$rejected",
                )
            }
            // Full-pipeline capstone (decision #32) — CPU pass only: when the
            // espeak-ng bundle is staged, phonemize ON the device and verify byte
            // parity against the host corpus, then re-run one full round with the
            // real phonemizer for the end-to-end RTF.
            if (capstone) {
                val espeakLib = File(context.filesDir, "espeak/libespeak-ng.so")
                val espeakData = File(context.filesDir, "espeak/espeak-ng-data")
                if (espeakLib.isFile && espeakData.isDirectory) {
                    try {
                        val real =
                            com.moronigranja.localttsreader.tts.kokoro.EspeakPhonemizer(
                                libraryPath = espeakLib.absolutePath,
                                dataPath = espeakData.absolutePath,
                            )
                        log("on-device espeak-ng loaded (lib + data)")
                        var parity = true
                        for ((text, language, hostPhonemes) in entries) {
                            val devicePhonemes = real.phonemize(text, language)
                            if (devicePhonemes == hostPhonemes) {
                                log("phonemizer parity [$language]: MATCH (${devicePhonemes.length} chars)")
                            } else {
                                parity = false
                                log(
                                    "phonemizer parity [$language]: MISMATCH\n  host:   ${hostPhonemes.take(
                                        100,
                                    )}\n  device: ${devicePhonemes.take(100)}",
                                )
                            }
                        }
                        if (parity) {
                            val fullEngine =
                                KokoroEngine.open(
                                    spec = DefaultEngines.kokoro,
                                    packs = KokoroPacks.all,
                                    modelFile = File(models, "kokoro-model"),
                                    voicesFile = File(models, "kokoro-voices"),
                                    phonemizer = real,
                                    progress = { log("full open stage: $it") },
                                )
                            val fullJson = JSONArray()
                            for ((text, language, _) in entries) {
                                val voice = VOICES[language] ?: continue
                                var outcome: SynthesisOutcome? = null
                                val millis =
                                    measureTimeMillis {
                                        outcome = runBlocking { fullEngine.synthesize(SynthesisRequest(text, voice)) }
                                    }
                                val result = outcome as? SynthesisOutcome.Audio
                                val seconds =
                                    result
                                        ?.pcm
                                        ?.size
                                        ?.div(2.0)
                                        ?.div(KokoroEngine.SAMPLE_RATE) ?: 0.0
                                log(
                                    "full run [$language]: ${"%.2f".format(
                                        seconds,
                                    )}s audio in $millis ms, RTF=${"%.3f".format(millis / 1000.0 / seconds)}",
                                )
                                fullJson.put(
                                    JSONObject().put("language", language).put("synth_ms", millis).put(
                                        "rtf",
                                        millis / 1000.0 / seconds,
                                    ),
                                )
                            }
                            results.put("full_pipeline", fullJson)
                            fullEngine.close()
                        } else {
                            log("phonemizer parity FAILED — full-pipeline run skipped")
                        }
                        real.close()
                    } catch (e: Throwable) {
                        log("on-device espeak-ng unavailable: $e")
                    }
                } else {
                    log("espeak bundle not staged — skipping full-pipeline run")
                }
            }
            File(outDir, resultFileName).writeText(results.toString(2))
            log("$resultFileName written to $outDir")
            log("peak status: ${thermal.maxStatus}, headroom: ${thermal.maxHeadroom}")
            log("VmHWM: ${readVmHwm()} kB, totalPss: ${mem.totalPss} kB")
            log("DONE (candidate=$label)")
            engine.close()
            oracle?.close()
            true
        } catch (e: Throwable) {
            log("candidate $label unavailable: $e")
            false
        }
    }

    fun run(
        provider: OrtProvider,
        log: (String) -> Unit,
    ): Boolean =
        measure(
            label = provider.label,
            modelFileName = "kokoro-model",
            options = provider.options,
            oracleModelFileName = if (provider == OrtProvider.CPU) null else "kokoro-model",
            runs = if (provider == OrtProvider.CPU) RUNS else 1,
            capstone = provider == OrtProvider.CPU,
            resultFileName = "kokoro_results_${provider.label}.json",
            log = log,
        )

    /**
     * Runs a single precision candidate (D3 spike) on CPU EP, oracle-gated
     * against the pinned fp32. All precisions use the default session factory —
     * precision is a model-file axis, not an execution provider.
     */
    fun runPrecision(
        precision: ModelPrecision,
        log: (String) -> Unit,
    ): Boolean =
        measure(
            label = precision.label,
            modelFileName = precision.fileName,
            options = {},
            oracleModelFileName = "kokoro-model",
            runs = 1,
            capstone = false,
            resultFileName = "kokoro_precision_${precision.label}.json",
            log = log,
        )

    /**
     * The same precision candidates through the QNN HTP EP (D3 × D2 cross):
     * quantization is the NPU's native regime, so a QDQ/fp16 graph may
     * partition where the fp32 graph fell back. Oracle-gated against the
     * pinned fp32 on the CPU EP, like every other candidate.
     */
    fun runQnnPrecision(
        precision: ModelPrecision,
        log: (String) -> Unit,
    ): Boolean =
        measure(
            label = "qnn-htp-${precision.label}",
            modelFileName = precision.fileName,
            options = { so -> QnnEp.install(so) },
            oracleModelFileName = "kokoro-model",
            runs = 1,
            capstone = false,
            resultFileName = "kokoro_qnn_${precision.label}.json",
            log = log,
        )

    private fun readVmHwm(): Long {
        val line = File("/proc/self/status").readLines().firstOrNull { it.startsWith("VmHWM:") } ?: return -1
        return line.split(Regex("\\s+"))[1].toLongOrNull() ?: -1
    }

    private fun pcmToFloats(pcm: ByteArray): FloatArray {
        val out = FloatArray(pcm.size / 2)
        val buffer =
            java.nio.ByteBuffer
                .wrap(pcm)
                .order(java.nio.ByteOrder.LITTLE_ENDIAN)
                .asShortBuffer()
        for (i in out.indices) out[i] = buffer.get() / 32768.0f
        return out
    }

    /** Peak + mean absolute amplitude delta between two PCM float arrays. */
    private fun pcmDiff(
        a: FloatArray,
        b: FloatArray,
    ): Pair<Float, Float> {
        val n = minOf(a.size, b.size)
        var peak = 0.0f
        var total = 0.0
        for (i in 0 until n) {
            val d = abs(a[i] - b[i])
            if (d > peak) peak = d
            total += d
        }
        return peak to (if (n > 0) (total / n).toFloat() else 0f)
    }

    /** Answers phonemization from the precomputed corpus (host espeak-ng). */
    private class CorpusPhonemizer(
        private val corpus: Map<String, String>,
        private val languages: Set<String>,
    ) : Phonemizer {
        override fun phonemize(
            text: String,
            language: String,
        ): String = corpus[text] ?: throw PhonemizeException("corpus mismatch for text: '${text.take(40)}…'")

        override fun supportedLanguages(): Set<String> = languages
    }
}
