package com.moronigranja.localttsreader.spiketts

import android.content.Context
import android.os.Build
import android.os.Debug
import com.moronigranja.localttsreader.tts.DefaultEngines
import com.moronigranja.localttsreader.tts.SynthesisOutcome
import com.moronigranja.localttsreader.tts.SynthesisRequest
import com.moronigranja.localttsreader.tts.kokoro.KokoroEngine
import com.moronigranja.localttsreader.tts.kokoro.KokoroPacks
import com.moronigranja.localttsreader.tts.kokoro.PhonemizeException
import com.moronigranja.localttsreader.tts.kokoro.Phonemizer
import java.io.File
import kotlin.system.measureTimeMillis
import kotlinx.coroutines.runBlocking
import org.json.JSONArray
import org.json.JSONObject

/**
 * The Kokoro on-device benchmark (decisions #30 device half), shared by the
 * interactive [KokoroActivity] and the instrumented
 * `KokoroDeviceBenchmarkTest` (which runs on a locked/off screen — the
 * realistic player condition).
 *
 * Phonemization is the only excluded stage: the corpus ships pre-phonemized
 * raw espeak-ng output (host-generated by `:core-tts:kokoroGrainSpike`), and
 * a passthrough [Phonemizer] answers for the corpus texts. Everything
 * downstream — vocab filter, chunker, windows, ORT inference, trim, pause
 * insertion — runs verbatim in the engine.
 */
class KokoroBenchmarkRunner(private val context: Context) {

    companion object {
        const val RUNS = 3
        private val VOICES = mapOf("en-us" to "af_heart", "pt-br" to "pf_dora")
    }

    private val models = File(context.filesDir, "models")
    private val corpusFile = File(context.filesDir, "corpus.tsv")

    /** Runs the benchmark; returns true on success. Progress via [log]. */
    fun run(log: (String) -> Unit): Boolean {
        val outDir = context.getExternalFilesDir(null) ?: context.filesDir
        return try {
            check(File(models, "kokoro-model").isFile && File(models, "kokoro-voices").isFile) {
                "models not found under ${models.absolutePath} — stage them first (see build.md)"
            }
            check(corpusFile.isFile) { "corpus not found at ${corpusFile.absolutePath}" }

            val entries = corpusFile.readLines().mapNotNull { line ->
                val parts = line.split('\t')
                if (parts.size != 3) null else Triple(parts[0], parts[1], parts[2])
            }
            check(entries.isNotEmpty()) { "corpus.tsv is empty or malformed" }
            val lookup = entries.associate { it.first to it.third }
            val languages = entries.map { it.second }.toSet()
            log("device: ${Build.MANUFACTURER} ${Build.MODEL}, sdk ${Build.VERSION.SDK_INT}")
            log("corpus: ${entries.size} passages (${languages.sorted()}); phonemization = host-precomputed")

            val tOpen = System.currentTimeMillis()
            val engine = KokoroEngine.open(
                spec = DefaultEngines.kokoro,
                packs = KokoroPacks.all,
                modelFile = File(models, "kokoro-model"),
                voicesFile = File(models, "kokoro-voices"),
                phonemizer = CorpusPhonemizer(lookup, languages),
                progress = { log("open stage: $it (${System.currentTimeMillis() - tOpen} ms)") },
            )
            log("engine open: ${System.currentTimeMillis() - tOpen} ms (kokoro-model + voices, embedded vocab)")

            val thermal = ThermalProbe(context)
            thermal.start()
            val results = JSONObject()
            val runs = JSONArray()
            for (run in 1..RUNS) {
                val runJson = JSONObject().put("run", run)
                val passagesJson = JSONArray()
                for ((text, language, _) in entries) {
                    val voice = VOICES[language] ?: error("no voice mapped for corpus language '$language'")
                    var outcome: SynthesisOutcome? = null
                    val millis = measureTimeMillis {
                        outcome = runBlocking { engine.synthesize(SynthesisRequest(text, voice)) }
                    }
                    when (val result = outcome) {
                        null -> error("synthesis returned null outcome")
                        is SynthesisOutcome.Audio -> {
                            val seconds = result.pcm.size / 2.0 / KokoroEngine.SAMPLE_RATE
                            val rtf = millis / 1000.0 / seconds
                            passagesJson.put(JSONObject()
                                .put("language", language)
                                .put("voice", voice)
                                .put("synth_ms", millis)
                                .put("audio_seconds", seconds)
                                .put("rtf", rtf)
                                .put("samples", result.pcm.size / 2))
                            log("run $run [$language/$voice]: ${"%.2f".format(seconds)}s audio in " +
                                "$millis ms, RTF=${"%.3f".format(rtf)}")
                            Wav.write(File(outDir, "kokoro_run${run}_${language}.wav"),
                                pcmToFloats(result.pcm), KokoroEngine.SAMPLE_RATE)
                        }
                        is SynthesisOutcome.Failed -> error("synthesis failed [$language]: ${result.reason}")
                        SynthesisOutcome.Unavailable -> error("packs not ready on device")
                    }
                }
                runJson.put("passages", passagesJson)
                runs.put(runJson)
            }
            thermal.stop()
            val mem = Debug.MemoryInfo()
            Debug.getMemoryInfo(mem)
            results.put("runs", runs)
            results.put("vm_hwm_kb", readVmHwm())
            results.put("total_pss_kb", mem.totalPss)
            results.put("thermal_status_max", thermal.maxStatus)
            results.put("thermal_headroom_max", thermal.maxHeadroom)
            results.put("screen", "off/locked (instrumented)")
            results.put("threads", 6)
            results.put("device", "${Build.MANUFACTURER} ${Build.MODEL}")
            results.put("phonemization", "excluded (host-precomputed corpus; espeak-ng cost is ~ms/sentence)")

            // Full-pipeline capstone (decision #32): when the espeak-ng bundle
            // is staged, phonemize ON the device (the Android arm64 .so + data)
            // and verify byte parity against the host corpus, then re-run one
            // full round with the real phonemizer for the end-to-end RTF.
            val espeakLib = File(context.filesDir, "espeak/libespeak-ng.so")
            val espeakData = File(context.filesDir, "espeak/espeak-ng-data")
            if (espeakLib.isFile && espeakData.isDirectory) {
                try {
                    val real = com.moronigranja.localttsreader.tts.kokoro.EspeakPhonemizer(
                        libraryPath = espeakLib.absolutePath,
                        dataPath = espeakData.absolutePath,
                    )
                    log("on-device espeak-ng loaded (lib + data)")
                    var parity = true
                    for ((text, language, hostPhonemes) in entries) {
                        val devicePhonemes = real.phonemize(text, language)
                        if (devicePhonemes == hostPhonemes) {
                            log("phonemizer parity [$language]: MATCH (${devicePhonemes.length} chars)")
                        } else {
                            parity = false
                            log("phonemizer parity [$language]: MISMATCH\n  host:   ${hostPhonemes.take(100)}\n  device: ${devicePhonemes.take(100)}")
                        }
                    }
                    if (parity) {
                        val fullEngine = KokoroEngine.open(
                            spec = DefaultEngines.kokoro,
                            packs = KokoroPacks.all,
                            modelFile = File(models, "kokoro-model"),
                            voicesFile = File(models, "kokoro-voices"),
                            phonemizer = real,
                            progress = { log("full open stage: $it") },
                        )
                        val fullJson = JSONArray()
                        for ((text, language, _) in entries) {
                            val voice = VOICES[language] ?: continue
                            var outcome: SynthesisOutcome? = null
                            val millis = measureTimeMillis {
                                outcome = runBlocking { fullEngine.synthesize(SynthesisRequest(text, voice)) }
                            }
                            val result = outcome as? SynthesisOutcome.Audio
                            val seconds = result?.pcm?.size?.div(2.0)?.div(KokoroEngine.SAMPLE_RATE) ?: 0.0
                            log("full run [$language]: ${"%.2f".format(seconds)}s audio in $millis ms, RTF=${"%.3f".format(millis / 1000.0 / seconds)}")
                            fullJson.put(JSONObject().put("language", language).put("synth_ms", millis).put("rtf", millis / 1000.0 / seconds))
                        }
                        results.put("full_pipeline", fullJson)
                        fullEngine.close()
                    } else {
                        log("phonemizer parity FAILED — full-pipeline run skipped")
                    }
                    real.close()
                } catch (e: Throwable) {
                    log("on-device espeak-ng unavailable: $e")
                }
            } else {
                log("espeak bundle not staged — skipping full-pipeline run")
            }
            File(outDir, "kokoro_results.json").writeText(results.toString(2))
            log("kokoro_results.json written to $outDir")
            log("peak status: ${thermal.maxStatus}, headroom: ${thermal.maxHeadroom}")
            log("VmHWM: ${readVmHwm()} kB, totalPss: ${mem.totalPss} kB")
            log("DONE")
            engine.close()
            true
        } catch (e: Throwable) {
            log("FAILED: $e\n${e.stackTraceToString().lineSequence().take(6).joinToString("\n")}")
            false
        }
    }

    private fun readVmHwm(): Long {
        val line = File("/proc/self/status").readLines().firstOrNull { it.startsWith("VmHWM:") } ?: return -1
        return line.split(Regex("\\s+"))[1].toLongOrNull() ?: -1
    }

    private fun pcmToFloats(pcm: ByteArray): FloatArray {
        val out = FloatArray(pcm.size / 2)
        val buffer = java.nio.ByteBuffer.wrap(pcm).order(java.nio.ByteOrder.LITTLE_ENDIAN).asShortBuffer()
        for (i in out.indices) out[i] = buffer.get() / 32768.0f
        return out
    }

    /** Answers phonemization from the precomputed corpus (host espeak-ng). */
    private class CorpusPhonemizer(
        private val corpus: Map<String, String>,
        private val languages: Set<String>,
    ) : Phonemizer {
        override fun phonemize(text: String, language: String): String =
            corpus[text] ?: throw PhonemizeException("corpus mismatch for text: '${text.take(40)}…'")

        override fun supportedLanguages(): Set<String> = languages
    }

    private class ThermalProbe(private val context: Context) {
        var maxStatus = -1
        var maxHeadroom = 0.0f
        @Volatile private var running = false
        private var thread: Thread? = null

        fun start() {
            if (Build.VERSION.SDK_INT < 29) return
            running = true
            thread = Thread {
                try {
                    // android.os.ThermalManager is missing from the android-36
                    // compile jar; the class exists at runtime on API 29+.
                    val cls = Class.forName("android.os.ThermalManager")
                    val tm = context.getSystemService("thermalservice")!!
                    val statusM = cls.getMethod("getCurrentThermalStatus")
                    val headroomM = cls.getMethod("getThermalHeadroom", Int::class.javaPrimitiveType)
                    while (running) {
                        try {
                            val s = statusM.invoke(tm) as Int
                            if (s > maxStatus) maxStatus = s
                            val h = headroomM.invoke(tm, 0) as Float
                            if (h > maxHeadroom) maxHeadroom = h
                        } catch (e: Exception) {
                            android.util.Log.d("KokoroSpike", "thermal sample skipped: $e")
                        }
                        Thread.sleep(500)
                    }
                } catch (e: ClassNotFoundException) {
                    android.util.Log.d("KokoroSpike", "thermal probe unavailable (no ThermalManager class): $e")
                } catch (e: Throwable) {
                    android.util.Log.d("KokoroSpike", "thermal probe failed: $e")
                }
            }.also { it.isDaemon = true; it.start() }
        }

        fun stop() {
            running = false
            thread?.join(2000)
        }
    }
}
